ALTER TABLE `ospos_customers` ADD COLUMN `init_balance` DOUBLE NOT NULL DEFAULT '0';
ALTER TABLE `ospos_suppliers` ADD COLUMN `init_balance` DOUBLE NOT NULL DEFAULT '0';
ALTER TABLE `ospos_items`
	ADD COLUMN `percentage` FLOAT UNSIGNED ZEROFILL NOT NULL DEFAULT 0,
	ADD COLUMN `extra_percentage` FLOAT UNSIGNED NOT NULL DEFAULT 0,
	ADD COLUMN `bonus` VARCHAR(10) NOT NULL DEFAULT '1-0';

